# #Q1
# fruits=[]
# f1=input("Enter Fruit name")
# fruits.append(f1)
# f2=input("Enter Fruit name")
# fruits.append(f2)
# f3=input("Enter Fruit name")
# fruits.append(f3)
# f4=input("Enter Fruit name")
# fruits.append(f4)
# f5=input("Enter Fruit name")
# fruits.append(f5)
# f6=input("Enter Fruit name")
# fruits.append(f6)
# f7=input("Enter Fruit name")
# fruits.append(f7)
# print(fruits)

# #Q2
# marks=[]
# m1=int(input("Enter your Mark"))
# marks.append(m1)
# m2=int(input("Enter your Mark"))
# marks.append(m2)
# m3=int(input("Enter your Mark"))
# marks.append(m3)
# m4=int(input("Enter your Mark"))
# marks.append(m4)
# m5=int(input("Enter your Mark"))
# marks.append(m5)
# m6=int(input("Enter your Mark"))
# marks.append(m6)

# marks.sort()
# print(marks)

#Q4
li=[2,54,23,37]
# sum=li[0] + li[1] + li[2] + li[3]  #manually
# print(sum)
print(sum(li)) #using sum function

#Q5
a=(7,0,8,0,0,9)
cn=a.count(0)
print(cn)